# Generated by Django 5.0.6 on 2024-07-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0002_post_created_at_alter_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='slug-is', unique=True),
            preserve_default=False,
        ),
    ]
